config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  get '/about', to: 'home#about'
  resources :medics, only: %i[new create]

  devise_for :users, path: '/admin'
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_confirmation_status.rb
# frozen_string_literal: true

# Status enum provider concern
module HasConfirmationStatus
  extend ActiveSupport::Concern
  included do
    enum status: { approved: 'approved', rejected: 'rejected', pending: 'pending' }
  end
end

app/models/concerns/has_status.rb
# frozen_string_literal: true

# Status enum provider concern
module HasStatus
  extend ActiveSupport::Concern
  included do
    enum status: { approved: 'approved', rejected: 'rejected', pending: 'pending' }
  end
end

app/models/medic.rb
# frozen_string_literal: true

# Medic entity model
class Medic < ApplicationRecord
  include HasConfirmationStatus

  before_create :set_default_status
  validates :name, :crm, :phone, :email, presence: true

  def set_default_status
    self.status = 'pending'
  end
end

app/models/patient.rb
# frozen_string_literal: true

# Patient entity model
class Patient < ApplicationRecord
  include HasConfirmationStatus

  before_create :set_default_status
  validates :name, :crm, :phone, :email, presence: true

  def set_default_status
    self.status = 'pending'
  end
end

app/models/user.rb
# frozen_string_literal: true

# User is a model managing people that has access to platform
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :lockable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController is a base controller for rails app
class ApplicationController < ActionController::Base
  def set_admin_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(_options = {})
    { locale: I18n.locale }
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < PublicController
  def index; end

  def about; end
end

app/controllers/medics_controller.rb
# frozen_string_literal: true

# TODO: Add i18n on future if needed

class MedicsController < PublicController
  def new
    @medic = Medic.new
  end

  def create
    @medic = Medic.new(medic_params)
    if @medic.save
      flash[:notice] = 'Cadastro realizado com sucesso!'
      redirect_to new_medic_path
      return
    end

    flash.now[:error] = 'Existem alguns dados com erro no cadastro'
    render action: :new
  end

  private

  def medic_params
    params.require(:medic).permit(:name, :crm, :phone, :email, :profession)
  end
end

app/controllers/public_controller.rb
# frozen_string_literal: true

class PublicController < ActionController::Base
  layout 'public'
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/css_helper.rb
# frozen_string_literal: true

module CssHelper
  def class_name(css_map)
    css_map.find_all(&:last).map(&:first).join(' ')
  end
end

app/helpers/error_helper.rb
# frozen_string_literal: true

module ErrorHelper
  def field_error?(model, field)
    return (model.errors.messages.key? field) && !model.errors.messages[field].empty? if model.errors

    false
  end

  def field_errors(object, field)
    if object.errors
      messages = object.errors.messages
      return messages[field] if messages.key? field
    end
    []
  end
end

app/views/home/about.html.erb
<section class="hero is-medium is-default is-bold">
    <div class="hero-body">
        <div class="container">
                    <h1 class="title is-3 is-bold is-spaced has-text-centered">
                      Sobre nós
                    </h1>

                    <div class="content subtitle is-5 is-muted has-text-centered">
                        <p>
                            Iniciamos este projeto com o intuito de fornecer atendimentos de saúde mental gratuito por vídeo conferência para profissionais que estejam
                            na linha de frente neste momento difícil da pandemia, enfrentando situações de mudanças, medo, luto e incertezas.
                        </p>
                                 
                        <p>
                            As mudanças nas rotinas geram extremo desconforto em todos em situação de quarentena, porém, profissionais da área da saúde não só sofrem
                            estas mudanças em suas rotinas domésticas como também no trabalho, com deslocamento de setores e funções, mudanças de fluxos e cargas 
                            horárias excessivas.
                        </p>

                        <p>
                            O medo de uma doença nova que pouco conhecemos, de um surto ou uma doença grave de difícil controle gera medo e insegurança acerca de
                            nossas possibilidades de exercer nossa profissão e por nossa própria saúde também.
                        </p>

                        <p>
                            O luto da perda de nossos pacientes e de colegas de trabalho gera profunda tristeza e igualmente medo.
                            A incerteza do que esta por vir, quanto tempo vai durar e qual será a dimensão dos danos que vamos viver.
                        </p>
                      
                        <p>
                            Todas estas situações podem gerar sensações de medo, tristeza, angústia e ansiedade, irritabilidade, insônia, pensamentos de morte,
                            redução da concentração e distraibilidade.
                        </p>

                        <p>
                            Contamos com atendimentos de acolhimento multiprofissional e consultas psiquiátricas para ajudar nossos colegas que travam estas batalhas
                            tão intensa, árdua  e desgastante.

                            
                        </p>
                      
                        <p>
                            Não pertencemos a nenhum orgão Público ou Filantrópico, apenas profissionais da Saúde Mental com o intuito de ajudar outros colegas.
                            Não estamos na Linha de frente mas estamos na Retaguarda. 
  
                        </p>
                      
                        <p>
                            Precisa de ajuda? Quer se voluntariar também?  
                        </p>
                    </div>
                </div>
        </div>
    </div>
</section>

app/views/home/index.html.erb
<section class="hero is-fullheight is-default is-bold">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column is-5 is-offset-1 landing-caption">
                    <h1 class="title is-3 is-bold is-spaced has-text-centered">
                      ASMP - Atendimento de Saúde Mental em Pandemia
                    </h1>
                    <h2 class="subtitle is-5 is-muted has-text-centered">
                    Somos profissionais da Saúde Mental com o intuito de ajudar outros colegas.
                    Não estamos na Linha de frente mas estamos na Retaguarda.
                    </h2>
                    <div class="buttons">
                        <%= link_to "Precisa de ajuda?", new_medic_path, remote: true, :class => "button cta is-medium is-offset-1 is-rounded primary-btn raised" %>
                        <%= link_to "Quer se voluntariar?", new_medic_path, remote: true, :class => "button cta is-medium is-rounded" %>
                    </div>
                </div>
                <div class="column is-5">
                    <figure class="image is-4by3">
                        <img src="/images/hands.png" alt="Mãos coloridas, unidas">
                    </figure>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ASMP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<html>
    <head>
       <%= stylesheet_link_tag "public" %>
    </head>
    <body>
        <!-- headers, navbar e etc -->
        <%= render 'shared/navbar' %>
        <section id="body">
            <%= yield %>
        </section>
        <!-- footer e etc -->
        <%= render 'shared/footer' %>
    </body>
    <%= javascript_include_tag "public" %>
</html>

app/views/medics/_form.html.erb
<%= form_with model: medic, url: url, local: true, class: 'container' do |form| %>
    <div class="field">
        <%= form.label :name, class: 'label' %>
        <div class="control">
            <%= form.text_field :name, class: class_name(input: true, 'is-danger': field_error?(@medic, :crm))  %>
        </div>
        <%= render 'shared/field_errors', field: :name, errors: field_errors(@medic, :name) %>
    </div>

    <div class="field">
        <%= form.label :profession, class: 'label' %>
        <div class="control">
            <%= form.text_field :profession, class: class_name(input: true, 'is-danger': field_error?(@medic, :crm)) %>
        </div>
        <%= render 'shared/field_errors', field: :profession, errors: field_errors(@medic, :profession) %>
    </div>


    <div class="field">
        <%= form.label :crm, class: 'label' %>
        <div class="control">
            <%= form.text_field :crm, class: class_name(input: true, 'is-danger': field_error?(@medic, :crm)) %>
        </div>
        <%= render 'shared/field_errors', field: :crm, errors: field_errors(@medic, :crm) %>
    </div>
    <div class="field">
        <%= form.label :phone, class: 'label' %>
        <div class="control">
            <%= form.telephone_field :phone, class: class_name(input: true, 'is-danger': field_error?(@medic, :crm)) %>
        </div>
        <%= render 'shared/field_errors', field: :phone, errors: field_errors(@medic, :phone) %>
    </div>

    <div class="field">
        <%= form.label :email, class: 'label' %>
        <div class="control">
            <%= form.email_field :email, class: class_name(input: true, 'is-danger': field_error?(@medic, :crm))%>
        </div>
        <%= render 'shared/field_errors', field: :email, errors: field_errors(@medic, :email) %>
    </div>

    <div class="field">
        <div class="control">
            <%= form.submit class: 'button is-primary' %>
        </div>
    </div>
<% end %>

app/views/medics/new.html.erb
<section class="container">
    <h3 class="title">Quer se voluntariar? Entraremos em contato</h3>
    <% if flash[:notice] %>
        <div class="message is-info">
            <div class="message-body">
                <p>
                    <%= flash[:notice] %>
                </p>
            </div>
        </div>
    <% end  %>
    <% if flash[:error] %>
        <div class="message is-danger">
            <div class="message-body">
                <p><%= flash[:error] %></p>
            </div>
        </div>
    <% end %>
    <%= render 'form', medic: @medic, url: medics_path %>
</section>

app/views/shared/_field_errors.html.erb
<% unless errors.empty? %>
<div id="error-<%= field.to_s %>" class="error">
    <ul class="error-list">
    <% errors.each do |message| %>
        <li class="error-item"><%= message %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-dark">
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="footer-column">
                    <div class="footer-header">
                        <h3>Iniciativa</h3>
                    </div>
                    <ul class="link-list">
                        <li>
                            <%= link_to "Sobre", about_path, remote: true %>
                        </li>
                    </ul>
                    <ul class="link-list">
                        <li>
                            <%= link_to "Área administrativa", user_session_path, remote: true %>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="column">
                <div class="footer-column">
                    <div class="footer-header">
                        <h3>Redes sociais</h3>
                    </div>
                    <ul class="link-list">
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar is-fresh is-transparent no-shadow" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="/images/logo_cropped.png">
                ASMP - Atendimento de Saúde Mental em Pandemia
            </a>

            <a class="navbar-item is-hidden-desktop is-hidden-tablet">
                <div id="menu-icon-wrapper" class="menu-icon-wrapper" style="visibility: visible;">
                    <svg width="1000px" height="1000px">
                        <path class="path1" d="M 300 400 L 700 400 C 900 400 900 750 600 850 A 400 400 0 0 1 200 200 L 800 800"></path>
                        <path class="path2" d="M 300 500 L 700 500"></path>
                        <path class="path3" d="M 700 600 L 300 600 C 100 600 100 200 400 150 A 400 380 0 1 1 200 800 L 800 200"></path>
                    </svg>
                    <button id="menu-icon-trigger" class="menu-icon-trigger"></button>
                </div>
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbar-menu" class="navbar-menu is-static">
            <div class="navbar-end">
                <%= link_to "Home", root_path, remote: true, :class => "navbar-item is-secondary modal-trigger" %>
                
                <%= link_to "Sobre", about_path, remote: true, :class => "navbar-item is-secondary modal-trigger" %>

                <a href="/admin/sign_in" class="navbar-item">
                    <span class="button signup-button rounded secondary-btn raised">
                       Área administrativa 
                    </span>
                </a>
            </div>
        </div>
    </div>
</nav>